#
# Module manifest for module 'Organize'
#
# Generated by: James Brundage
#
# Generated on: 1/4/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Organize.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '18648885-026a-4806-a040-9327af9f40df'

# Author of this module
Author = 'James Brundage'

# Company or vendor of this module
CompanyName = 'Start Automating'

# Copyright statement for this module
Copyright = '2026 Start Automating'

# Description of the functionality provided by this module
Description = 'Organize objects any way you want - Fast PowerShell Grouping and Filtering'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @('Organize.types.ps1xml')

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('Organize.format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-Organized'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Organize',
        'Organized',
        'Organizer',
        
        'Get-Organize',
        'Get-Organizer',

        'Group-Organize',
        'Group-Organized',
        'Group-Organizer',

        'Organise',
        'Organised',
        'Organiser',

        'Get-Organise',
        'Get-Organised',
        'Get-Organiser',

        'Group-Organise',
        'Group-Organised',
        'Group-Organised'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Organizer', 'Group')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/StartAutomating/Organize/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/StartAutomating/Organize'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'

## Organize 0.1:

Organize objects any way you want. (#1)

Organize is a fast object organizer that lets you organize by multiple properties and scripts.

* It has a basic build (#2)
* It has a GitHub action (#3)
* It consists of a single command, `Get-Organized` (#4)  
  * `Get-Organized` returns an `Organizer` object
  * `Get-Organized` has many aliases (`Organize`, `Organizer`, `Organized`, `Organise`, `Organiser`, `Organised` etc) (#9)
* `Organizer`
  * `Organizer.Output` has the organized output (#5)
  * `Organizer.Input` gets or sets the organizer input (#6)
  * `Organizer.By` sets or sets the organizer criteria (#7) 
  * `Organizer.DefaultDisplay` shows `Input`, `By`, `Output`(#8)
  * `Organizer` has table and list formatters (#15)
* Organize has several GitHub community standard files:
  * Organize Code of Conduct (#10)
  * Organize Contributing (#11)
  * Organize Security (#12)
  * Organize Sponsorship (#13)
  * Organize README (#14)

'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

